In [1]:
import pandas as pda
fname="D:/python demo/lesson.csv"
dataf=pda.read_csv(fname,encoding="gbk")


In [2]:
dataf

序号 实战 课时数 是否促销 是否提供配套资料 销量
0    1  是   多    是        否  高
1    2  否   少    是        是  低
2    3  是   少    是        否  低
3    4  是   多    否        否  低
4    5  是   少    否        是  高
5    6  是   多    是        是  高
6    7  否   多    是        否  低
7    8  否   少    是        是  高
8    9  是   多    是        否  高
9   10  否   少    否        否  低
10  11  是   少    否        否  高
11  12  否   多    是        否  低
12  13  是   少    否        是  高
13  14  是   多    否        是  高
14  15  否   少    是        是  低
15  16  是   多    否        否  低
16  17  是   多    否        否  低
17  18  是   多    否        是  高
18  19  否   多    是        否  高
19  20  是   少    否        是  低
20  21  是   多    否        否  高
21  22  否   少    是        是  低
22  23  否   少    否        否  低
23  24  否   多    是        是  高
24  25  是   少    否        是  高
25  26  是   多    否        否  低
26  27  是   多    是        是  高
27  28  否   少    否        否  低
28  29  是   少    是        是  高

In [3]:
type(dataf)

pandas.core.frame.DataFrame

In [4]:

x=dataf.iloc[:,1:5].values
y=dataf.iloc[:,5].values


In [5]:
x

array([['是', '多', '是', '否'],
       ['否', '少', '是', '是'],
       ['是', '少', '是', '否'],
       ['是', '多', '否', '否'],
       ['是', '少', '否', '是'],
       ['是', '多', '是', '是'],
       ['否', '多', '是', '否'],
       ['否', '少', '是', '是'],
       ['是', '多', '是', '否'],
       ['否', '少', '否', '否'],
       ['是', '少', '否', '否'],
       ['否', '多', '是', '否'],
       ['是', '少', '否', '是'],
       ['是', '多', '否', '是'],
       ['否', '少', '是', '是'],
       ['是', '多', '否', '否'],
       ['是', '多', '否', '否'],
       ['是', '多', '否', '是'],
       ['否', '多', '是', '否'],
       ['是', '少', '否', '是'],
       ['是', '多', '否', '否'],
       ['否', '少', '是', '是'],
       ['否', '少', '否', '否'],
       ['否', '多', '是', '是'],
       ['是', '少', '否', '是'],
       ['是', '多', '否', '否'],
       ['是', '多', '是', '是'],
       ['否', '少', '否', '否'],
       ['是', '少', '是', '是']], dtype=object)

In [6]:
y

array(['高', '低', '低', '低', '高', '高', '低', '高', '高', '低', '高', '低', '高',
       '高', '低', '低', '低', '高', '高', '低', '高', '低', '低', '高', '高', '低',
       '高', '低', '高'], dtype=object)

In [9]:
type(y)

numpy.ndarray

In [10]:
for i in range(0,len(x)):
    for j in range(0,len(x[i])):
        thisdata=x[i][j]
        if(thisdata=="是" or thisdata=="多" or thisdata=="高"):
            x[i][j]=int(1)
        else:
            x[i][j]=int(-1)
for i in range(0,len(y)):
    thisdata=y[i]
    if(thisdata=="高"):
        y[i]=1
    else:
        y[i]=-1


In [11]:
x

array([[1, 1, 1, -1],
       [-1, -1, 1, 1],
       [1, -1, 1, -1],
       [1, 1, -1, -1],
       [1, -1, -1, 1],
       [1, 1, 1, 1],
       [-1, 1, 1, -1],
       [-1, -1, 1, 1],
       [1, 1, 1, -1],
       [-1, -1, -1, -1],
       [1, -1, -1, -1],
       [-1, 1, 1, -1],
       [1, -1, -1, 1],
       [1, 1, -1, 1],
       [-1, -1, 1, 1],
       [1, 1, -1, -1],
       [1, 1, -1, -1],
       [1, 1, -1, 1],
       [-1, 1, 1, -1],
       [1, -1, -1, 1],
       [1, 1, -1, -1],
       [-1, -1, 1, 1],
       [-1, -1, -1, -1],
       [-1, 1, 1, 1],
       [1, -1, -1, 1],
       [1, 1, -1, -1],
       [1, 1, 1, 1],
       [-1, -1, -1, -1],
       [1, -1, 1, 1]], dtype=object)

In [12]:
y

array([1, -1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1, -1, -1, 1, 1,
       -1, 1, -1, -1, 1, 1, -1, 1, -1, 1], dtype=object)

In [13]:
#容易出错的地方，需要进行格式转化
xf=pda.DataFrame(x)
yf=pda.DataFrame(y)
x2=xf.values.astype(int)
y2=yf.values.astype(int)


In [14]:
#建立决策树
from sklearn.tree import DecisionTreeClassifier as DTC
dtc=DTC(criterion="entropy")
dtc.fit(x2,y2)



DecisionTreeClassifier(criterion='entropy')

In [16]:
dtc.score(x2,y2)

0.8620689655172413

In [15]:
#直接预测销量高低
import numpy as npy
x3=npy.array([[1,-1,-1,1],[1,1,1,1],[-1,1,-1,1]])
rst=dtc.predict(x3)
print(rst)

[ 1  1 -1]


In [17]:

from sklearn.tree import export_graphviz
from six import StringIO
with open("D:/tree.dot","w") as file:
    file=export_graphviz(dtc,feature_names=["combat","num","promotion","data"],out_file=file)


In [26]:
import pydotplus
from sklearn.tree import export_graphviz
dot_data=export_graphviz(dtc,out_file=None,feature_names=["combat","num","promotion","data"],filled=True,impurity=False)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_png("D:/python demo/tree.png")

True