方差选择法

In [1]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data[0:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [2]:
#方差选择法，返回值为特征选择后的数据 
#参数threshold为方差的阈值
selector = VarianceThreshold(threshold=3).fit(iris.data, iris.target)
data = selector.transform(iris.data)
print(data[0:5])
print(selector.variances_)


[[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]]
[0.68112222 0.18871289 3.09550267 0.57713289]


随机森林法

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import numpy as np 
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
#将data分为特征和类标 x,y = data.ix[:,1:],data.ix[:,0] 
#将数据集分为训练集和测试集
train_x,test_x,train_y,test_y = train_test_split(iris.data, iris.target,test_size=0.3,random_state=1)
#定义一个由10000颗决策树组成的随机森林模型
rf_model = RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1)
#训练
rf_model.fit(train_x,train_y)
#获取特征的重要性
importances = rf_model.feature_importances_
#对特征的重要性进行排序
indices = np.argsort(importances)[::-1]
names = [iris.feature_names[i] for i in indices]
print(names)
print(importances)

['petal width (cm)', 'petal length (cm)', 'sepal length (cm)', 'sepal width (cm)']
[0.10476017 0.02480179 0.42498016 0.44545788]


相关系数法

In [7]:
iris = load_iris()
iris.df = pd.DataFrame(iris.data,columns=['petal width (cm)', 'petal length (cm)', 'sepal length (cm)', 'sepal width (cm)'])
iris.tg= pd.DataFrame(iris.target,columns=['label'])

In [8]:
result = pd.concat([iris.df, iris.tg], axis=1) 
print(result)

     petal width (cm)  petal length (cm)  sepal length (cm)  sepal width (cm)  \
0                 5.1                3.5                1.4               0.2   
1                 4.9                3.0                1.4               0.2   
2                 4.7                3.2                1.3               0.2   
3                 4.6                3.1                1.5               0.2   
4                 5.0                3.6                1.4               0.2   
..                ...                ...                ...               ...   
145               6.7                3.0                5.2               2.3   
146               6.3                2.5                5.0               1.9   
147               6.5                3.0                5.2               2.0   
148               6.2                3.4                5.4               2.3   
149               5.9                3.0                5.1               1.8   

     label  
0        0  
1

In [10]:
corr = result.corr()
corrlabel = corr['label']
print(corrlabel)

petal width (cm)     0.782561
petal length (cm)   -0.426658
sepal length (cm)    0.949035
sepal width (cm)     0.956547
label                1.000000
Name: label, dtype: float64


In [12]:
corrlabel[abs(corrlabel)>0.5].sort_values

<bound method Series.sort_values of petal width (cm)     0.782561
sepal length (cm)    0.949035
sepal width (cm)     0.956547
label                1.000000
Name: label, dtype: float64>